### ISSUE TITLE
Use Bulma CSS to improve the styling of this application in any way you see fit!

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/introducing-the-geosearch-command#13]
The application uses Bulma, and has very basic styling.  We've received a contribution to improve this as part of Hacktoberfest, and we'd love to see someone build on this start point!

https://bulma.io/

In terms of guidance for this specific issue, please stick to Bulma and don't introduce other dependencies or any sort of front end build process. I imagine any custom CSS would go in static/app.css.

This is part of our participation in Hacktoberfest 2022.  Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us?  Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention us in the comments and ask to be assigned.

**Comment by Sparsh47** [comment]
can you assign this issue to me?

**Comment by SuzeShardlow** [comment]
Hi @Sparsh47, I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/

**Comment by SuzeShardlow** [comment]
This issue is available and up for grabs :)

**Comment by mcbianconi** [comment]
May I grab this one?

**Comment by SuzeShardlow** [comment]
Hello @mcbianconi, I see you have opened a PR against a different issue. We are only allocating one issue per person to ensure more people have a chance, so I'm leaving this up for grabs for other people in the community to work on :)

**Comment by SuzeShardlow** [comment]
Hi @mcbianconi, yes, go ahead :)  I've assigned this to you, looking forward to seeing your PR in the next couple of days. Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/

**Comment by SuzeShardlow** [comment]
This issue is open and up for grabs :) if you would like to work on it, please reply and tag me and @simonprickett.
