### ISSUE TITLE
Error building docker image: Missing hiredis dependencies

### ISSUE THREAD

**Issue by mcbianconi** [redis-developer/introducing-the-geosearch-command#16]
Project depends on hiredis but the docker base image (python:3.10-slim-buster) does not have its requirements:
-  gcc
- python3-dev

**Comment by mcbianconi** [comment]
Made a PR here https://github.com/redis-developer/introducing-the-geosearch-command/pull/17

**Comment by simonprickett** [comment]
Thanks for raising this, I'm able to reproduce and will look into it.
