### ISSUE TITLE
Update images in the README file

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/introducing-the-geosearch-command#20]
There are several images of the running application in the README file.  Since this file was originally written, the design of the application has been updated (thanks to Hacktoberfest participants!).  Update each image in `README.md` with a new version that reflects the updated application design.  Be sure to replicate the state of the application in each image correctly.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by RajputUsman** [comment]
Could you assign this to me? @simonprickett @SuzeShardlow

**Comment by SuzeShardlow** [comment]
Yes @rajputusman, it's yours :)  Please check out our guidelines at https://redis.io/community/hacktoberfest/ and we look forward to receiving your PR in a couple of days :)

**Comment by droffilc1** [comment]
Hello @simonprickett @SuzeShardlow I would like to work on this issue

**Comment by SuzeShardlow** [comment]
Hi @droffilc1, I've assigned this to you, looking forward to seeing your PR in the next couple of days :) Have fun and please check out our guidelines:

https://redis.io/community/hacktoberfest/
