### ISSUE TITLE
Add an extra route that returns the geo position for a given station name

### ISSUE THREAD

**Issue by simonprickett** [redis-developer/introducing-the-geosearch-command#4]
Add an extra route to the Flask backend that retrieves the geo position for a given station using the Redis `GEOPOS` command.

The route should be at `/api/position/<station name>` e.g. `/api/position/Concord`.

Check out the documentation for the Redis `GEOPOS` command here: https://redis.io/commands/geopos

This is part of our participation in Hacktoberfest 2021.  Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us?  Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by SuzeShardlow** [comment]
Hi @s-kamil yes, I will assign this to you.  Please make sure you read the guidance on our Hacktoberfest page linked in the issue, and open your pull request within two days.  Thanks and have fun!  :)
